# ==========================================
# application.yml  (Opción B - import externo)
# - Mantiene perfiles dev/test/prod en el MISMO archivo.
# - Importa overrides desde ${APPS_PROPS}/cse-seguros-empresask.yml si existe.
# - Perfil activo por SPRING_PROFILES_ACTIVE (default: dev).
# ==========================================

spring:
  application:
    name: ms-pseg-cotizaciones-mantenedor
  config:
    import:
      - optional:file:${APPS_PROPS}/Config/ms-pseg-cotizaciones-mantenedor.yml
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

management:
  endpoints:
    web:
      exposure:
        include: "health,info"
  endpoint:
    health:
      probes:
        enabled: true

springdoc:
  api-docs:
    enabled: ${SWAGGER_ENABLED:true}
  swagger-ui:
    enabled: ${SWAGGER_ENABLED:true}

# =========================
# PERFIL: prod
# =========================
---
spring:
  config:
    activate:
      on-profile: "prod"

  datasource:
    jndi-name: java:comp/env/jdbc/ocimarcelo

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate.dialect: org.hibernate.dialect.OracleDialect
      hibernate.temp.use_jdbc_metadata_defaults: false

server:
  servlet:
    context-path: /ms-pseg-cotizaciones-mantenedor

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

logging:
  level:
    org.springframework: INFO
    cl.bch.segurosempresas: INFO
    org.hibernate: INFO

# (Si usan OTLP en QA/PROD, muévelo al YAML externo del banco)
# management:
#   tracing:
#     sampling:
#       probability: 0.1
#   otlp:
#     tracing:
#       endpoint: ${OTEL_EXPORTER_OTLP_ENDPOINT:http://otel-collector:4318/v1/traces}

# =========================
# PERFIL: test (sin prefijo)
# =========================
---
spring:
  config:
    activate:
      on-profile: "test"

server:
  servlet:
    context-path: /   # sin prefijo para tests

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

logging:
  level:
    org.springframework: DEBUG
    cl.bch.segurosempresas: DEBUG
    org.hibernate: DEBUG

# =========================
# PERFIL: dev
# =========================
---
spring:
  config:
    activate:
      on-profile: "dev"

  datasource:
    jndi-name: java:comp/env/jdbc/ocimarcelo

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate.dialect: org.hibernate.dialect.OracleDialect
      hibernate.temp.use_jdbc_metadata_defaults: false

server:
  servlet:
    context-path: /ms-pseg-cotizaciones-mantenedor

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

logging:
  level:
    org.springframework: DEBUG
    cl.bch.segurosempresas: DEBUG
    org.hibernate: DEBUG
